language: ruby
rvm:
  - 2.3.1
services:
  - mongodb
install:
  - bundle install
before_script:
  - cp config/database.yml.travis config/database.yml
  - mongo smg_test --eval 'db.addUser("travis", "test");'
script:
  - bundle exec rake
